# Snowflake Automated Testing Pipeline - CDW_DEV
# By: Martin Palkovic
# Date: 2022-10-12
# Runs SQL code against a dev database, and will
# notify you in the PR if there are any
# syntax errors

name: Snowflake Testing Pipeline 

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /Snowflake/<your_dev_folder_here>
pool:
  vmImage: 'ubuntu-latest'
variables:
- group: snowflake_dev_credentials
jobs:
- job: Test_SQL_in_DEV_DATABASE
  workspace:
    clean: all
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.8'
    inputs:
      versionSpec: '3.8'
  - task: Bash@3
    displayName: 'Bash Script'
    inputs:
      targetType: 'inline'
      script: |
        echo 'Starting bash task'
        echo "ROOT_FOLDER $(ROOT_FOLDER)"
        python --version

        echo 'Step 1: Install schemachange'
        pip install schemachange --upgrade

        echo 'Step 2: Running schemachange'
        if schemachange -f $(ROOT_FOLDER) -a $(SNOWFLAKE_ACCOUNT) -u $(SNOWFLAKE_USERNAME) -r $(SNOWFLAKE_ROLE) -w $(SNOWFLAKE_WAREHOUSE) -d $(SNOWFLAKE_DATABASE) -c $(SNOWFLAKE_DATABASE).SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table ; then
        echo 'Test build is complete, you can merge this PR!'
        else
        exit 1
        fi
    env:
      SNOWFLAKE_PASSWORD: $(SNOWFLAKE_PASSWORD)