# Azure CI pipeline that lints all YAML files during a PR.
# See the yamllint GitHub for more info: [yamllint](https://github.com/adrienverge/yamllint)
name: yamllint PR Check

parameters:
  - name: jobName
    default: 'yamllintPR'
  - name: jobDisplay
    default: 'Lint .yml files with yamllint'

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: ${{ parameters.jobName}}
    timeoutInMinutes: 10
    displayName: ${{ parameters.jobDisplay }}

    workspace:
      clean: outputs

    steps:
      # Checkout repo
      - checkout: self
        fetchDepth: 1
        clean: true

      # Install yamllint
      - script: |
          pip install yamllint
        displayName: Download yamllint

      # Test yamllint installation and list all .yml files in the repo
      - script: |
          yamllint --version
          git ls-files | grep \.yml
        displayName: Test yamllint Install, list all .yml files

      # Lint YAML
      - script: |
          git ls-files | grep \.yml | yamllint .
        displayName: Lint .yml files
