version: '3.9'

services:
  SQL-Server:
    image: mcr.microsoft.com/mssql/server:2022-latest # Or whatever version you want
    container_name: SQL_Server_Dev_Environment
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=-xyKTjBx3Gk1k9zi5I39!
      # - MSSQL_PID=Developer
      # - MSSQL_AGENT_ENABLED=True

  python:
    container_name: SQL_Server_Python_Script
    build: ./
    command: python3 ./SQL_Server_ForLoop.py

  # python:
  #   image: python:latest
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - type: bind
  #     - source: .
  #   links:
  #     - 'SQL-Server'
  #   command: python3 ./SQL_Server_ForLoop.py
  
