# This pipeline uses the SnowSQL CLI to deploy code to Snowflake that is merged to main after PR approval.
# Note that this is the 'parent' pipeline, which calls the build.yml and deploy.yml files
# Note that this uses Azure DevOps flavoured YAML but could easily be modified to work with Github or GitLab

name: Snowflake CD Pipeline

variables:
- group: SnowSQL
- name: artifactName
  value: 'snowflakeTest'
- name: vmImage
  value: 'ubuntu-latest'  

trigger:
  branches:
    include:
    - main

stages:
- stage: Build
  jobs:
  - template: build.yml
    parameters:
      jobName: 'BuildSnowflakeObjects'
      artifactName: $(artifactName)
      vmImage: $(vmImage)

- stage: DEV
  variables:
  - name: database
    value: DEV
  - name: schema
    value: misc
  jobs:
  - template: deploy.yml
    parameters:
      jobName: DEV
      databaseName: $(database)
      vmImage: $(vmImage)
      environmentName: DEV

- stage: QA
  variables:
  - name: database
    value: QA
  - name: schema
    value: misc
  jobs:
  - template: deploy.yml
    parameters:
      jobName: QA
      databaseName: $(database)
      vmImage: $(vmImage)
      environmentName: QA

- stage: PROD
  variables:
  - name: database
    value: PROD
  jobs:
  - template: deploy.yml
    parameters:
      jobName: PROD
      databaseName: $(database)
      vmImage: $(vmImage)
      environmentName: PROD