# This pipeline uses SQLFluff to lint Snowflake SQL code during a pull request
# Note that this uses Azure DevOps flavoured YAML but could easily be modified to work with Github or GitLab

name: Pull Request check using SQLFluff

parameters:
  - name: jobName
    default: 'SnowflakeTest'
  - name: jobDisplay
    default: 'Lint repo with SQLFluff'

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: ${{ parameters.jobName }}
    timeoutInMinutes: 10
    displayName: ${{ parameters.jobDisplay }}

    workspace:
      clean: outputs

    steps:

    # Checkout repo
    - checkout: self
      fetchDepth: 10
      clean: true

      # Download and Install SnowSQL CLI
    - script: |
        pip install --upgrade pip
        pip install sqlfluff
      displayName: Download and Install SQLFLuff

      # Lint SQL
    - script: |
        git ls-files | grep \.sql | sqlfluff lint --dialect snowflake
      displayName: Analyzing the code with SQLFluff
